In [209]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import matplotlib as mpl
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
#small change

In [210]:
gamerID = 'gamer5'
dateCols = ['Datetime']
anots = pd.read_csv('./PPG_dataset/' + gamerID + '-annotations.csv', parse_dates=dateCols)
anots.dataframeName = gamerID + '-annotations'
anots.shape

(86, 3)

In [211]:
anots.head(30)

              Datetime                                      Event Value
0  2000-01-01 11:00:00  Stanford Sleepiness Self-Assessment (1-7)     3
1  2000-01-01 12:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
2  2000-01-01 13:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
3  2000-01-01 14:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
4  2000-01-01 15:00:00  Stanford Sleepiness Self-Assessment (1-7)     3
5  2000-01-01 16:00:00  Stanford Sleepiness Self-Assessment (1-7)     2
6  2000-01-01 17:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
7  2000-01-01 18:00:00  Stanford Sleepiness Self-Assessment (1-7)     2
8  2000-01-01 19:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
9  2000-01-01 20:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
10 2000-01-01 21:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
11 2000-01-01 22:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
12 2000-01-01 23:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
13 2000-01-02 00:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
14 2000-01-02 01:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
15 2000-01-02 02:00:00  Stanford Sleepiness Self-Assessment (1-7)     1
16 2000-01-02 03:00:00  Stanford Sleepiness Self-Assessment (1-7)     2
17 2000-01-02 04:00:00  Stanford Sleepiness Self-Assessment (1-7)     2
18 2000-01-02 05:00:00  Stanford Sleepiness Self-Assessment (1-7)     3
19 2000-01-02 06:00:00  Stanford Sleepiness Self-Assessment (1-7)     3
20 2000-01-02 07:00:00  Stanford Sleepiness Self-Assessment (1-7)     3
21 2000-01-02 08:00:00  Stanford Sleepiness Self-Assessment (1-7)     3
22 2000-01-02 09:00:00  Stanford Sleepiness Self-Assessment (1-7)     4
23 2000-01-02 10:00:00  Stanford Sleepiness Self-Assessment (1-7)     5
24 2000-01-02 11:00:00  Stanford Sleepiness Self-Assessment (1-7)     5
25 2000-01-02 09:02:00            Sleep-2-Peak Reaction Time (ms)   262
26 2000-01-02 08:02:00            Sleep-2-Peak Reaction Time (ms)   251
27 2000-01-02 07:02:00            Sleep-2-Peak Reaction Time (ms)   244
28 2000-01-02 06:02:00            Sleep-2-Peak Reaction Time (ms)   306
29 2000-01-02 05:01:00            Sleep-2-Peak Reaction Time (ms)   264

In [212]:
#!pip install neurokit2
import neurokit2 as nk
from datetime import datetime
ppg = pd.read_csv('./PPG_dataset/' + gamerID + '-ppg-2000-01-01.csv', delimiter=',', nrows = 1000000)
time1 = datetime.strptime(str(ppg.iloc[0]['Time']), '%H:%M:%S.%f')
time2 = datetime.strptime(str(ppg.iloc[-2]['Time']), '%H:%M:%S.%f')
difference = (time2 - time1).total_seconds()
print(difference, "seconds between", str(time1), "and", str(time2))
sample_rate = len(ppg['Red_Signal']) / difference
print(sample_rate)
signals, info = nk.ppg_process(ppg['Red_Signal'], sampling_rate=sample_rate)
#nk.ppg_plot(signals, info, static=True)
#nk.ppg_plot(signals, info, static=False)

10293.081625 seconds between 1900-01-01 12:54:44.096662 and 1900-01-01 15:46:17.178287
97.15263479220684

In [213]:
signals['PPG_Peaks'].value_counts()
signals['Timestamp'] = "2000-01-01 " + ppg['Time']
signals

,PPG_Raw,PPG_Clean,PPG_Rate,PPG_Quality,PPG_Peaks,Timestamp
0,686,9.825906,86.612463,0.697393,0,2000-01-01 12:54:44.096662
1,656,-66.620437,86.612463,0.697393,0,2000-01-01 12:54:44.100672
2,526,-141.377287,86.612463,0.697393,0,2000-01-01 12:54:44.100672
3,422,-212.469774,86.612463,0.697393,0,2000-01-01 12:54:44.101674
4,327,-277.635438,86.612463,0.697393,0,2000-01-01 12:54:44.102676
...,...,...,...,...,...,...
999995,623,40.813427,95.559969,0.892090,0,2000-01-01 15:46:17.161904
999996,615,36.731965,95.559969,0.892090,0,2000-01-01 15:46:17.162907
999997,608,33.949060,95.559969,0.892090,0,2000-01-01 15:46:17.178287
999998,602,32.189015,95.559969,0.892090,0,2000-01-01 15:46:17.178287
999999,596,31.072167,95.559969,0.892090,0,2000-01-01 15:46:17.193917

In [214]:
#nk.hrv(signals)

In [215]:
anots['Timestamp'] = pd.to_datetime(anots['Datetime'])
anots.drop('Datetime', axis=1, inplace=True)
signals['Timestamp'] = pd.to_datetime(signals['Timestamp'])
signals

,PPG_Raw,PPG_Clean,PPG_Rate,PPG_Quality,PPG_Peaks,Timestamp
0,686,9.825906,86.612463,0.697393,0,2000-01-01 12:54:44.096662
1,656,-66.620437,86.612463,0.697393,0,2000-01-01 12:54:44.100672
2,526,-141.377287,86.612463,0.697393,0,2000-01-01 12:54:44.100672
3,422,-212.469774,86.612463,0.697393,0,2000-01-01 12:54:44.101674
4,327,-277.635438,86.612463,0.697393,0,2000-01-01 12:54:44.102676
...,...,...,...,...,...,...
999995,623,40.813427,95.559969,0.892090,0,2000-01-01 15:46:17.161904
999996,615,36.731965,95.559969,0.892090,0,2000-01-01 15:46:17.162907
999997,608,33.949060,95.559969,0.892090,0,2000-01-01 15:46:17.178287
999998,602,32.189015,95.559969,0.892090,0,2000-01-01 15:46:17.178287
999999,596,31.072167,95.559969,0.892090,0,2000-01-01 15:46:17.193917

In [216]:
anots.dtypes

Event                object
Value                object
Timestamp    datetime64[ns]
dtype: object

In [217]:
signals.dtypes

PPG_Raw                 int64
PPG_Clean             float64
PPG_Rate              float64
PPG_Quality           float64
PPG_Peaks               int64
Timestamp      datetime64[ns]
dtype: object

In [218]:
signals

,PPG_Raw,PPG_Clean,PPG_Rate,PPG_Quality,PPG_Peaks,Timestamp
0,686,9.825906,86.612463,0.697393,0,2000-01-01 12:54:44.096662
1,656,-66.620437,86.612463,0.697393,0,2000-01-01 12:54:44.100672
2,526,-141.377287,86.612463,0.697393,0,2000-01-01 12:54:44.100672
3,422,-212.469774,86.612463,0.697393,0,2000-01-01 12:54:44.101674
4,327,-277.635438,86.612463,0.697393,0,2000-01-01 12:54:44.102676
...,...,...,...,...,...,...
999995,623,40.813427,95.559969,0.892090,0,2000-01-01 15:46:17.161904
999996,615,36.731965,95.559969,0.892090,0,2000-01-01 15:46:17.162907
999997,608,33.949060,95.559969,0.892090,0,2000-01-01 15:46:17.178287
999998,602,32.189015,95.559969,0.892090,0,2000-01-01 15:46:17.178287
999999,596,31.072167,95.559969,0.892090,0,2000-01-01 15:46:17.193917

In [219]:
anots.head(20)
sleepiness = anots.loc[anots['Event'] == 'Stanford Sleepiness Self-Assessment (1-7)']
sleepiness = sleepiness.reset_index().drop('index',axis=1)
sleepiness = pd.DataFrame({'Timestamp' : sleepiness['Timestamp'], 'Stanford Sleepiness Self-Assessment (1-7)' : sleepiness['Value']})
sleepiness

             Timestamp Stanford Sleepiness Self-Assessment (1-7)
0  2000-01-01 11:00:00                                         3
1  2000-01-01 12:00:00                                         1
2  2000-01-01 13:00:00                                         1
3  2000-01-01 14:00:00                                         1
4  2000-01-01 15:00:00                                         3
5  2000-01-01 16:00:00                                         2
6  2000-01-01 17:00:00                                         1
7  2000-01-01 18:00:00                                         2
8  2000-01-01 19:00:00                                         1
9  2000-01-01 20:00:00                                         1
10 2000-01-01 21:00:00                                         1
11 2000-01-01 22:00:00                                         1
12 2000-01-01 23:00:00                                         1
13 2000-01-02 00:00:00                                         1
14 2000-01-02 01:00:00                                         1
15 2000-01-02 02:00:00                                         1
16 2000-01-02 03:00:00                                         2
17 2000-01-02 04:00:00                                         2
18 2000-01-02 05:00:00                                         3
19 2000-01-02 06:00:00                                         3
20 2000-01-02 07:00:00                                         3
21 2000-01-02 08:00:00                                         3
22 2000-01-02 09:00:00                                         4
23 2000-01-02 10:00:00                                         5
24 2000-01-02 11:00:00                                         5

In [220]:
reaction_times = anots.loc[anots['Event'] == 'Sleep-2-Peak Reaction Time (ms)']
reaction_times = reaction_times.reset_index().drop('index',axis=1)
reaction_times

                              Event Value           Timestamp
0   Sleep-2-Peak Reaction Time (ms)   262 2000-01-02 09:02:00
1   Sleep-2-Peak Reaction Time (ms)   251 2000-01-02 08:02:00
2   Sleep-2-Peak Reaction Time (ms)   244 2000-01-02 07:02:00
3   Sleep-2-Peak Reaction Time (ms)   306 2000-01-02 06:02:00
4   Sleep-2-Peak Reaction Time (ms)   264 2000-01-02 05:01:00
5   Sleep-2-Peak Reaction Time (ms)   256 2000-01-02 04:04:00
6   Sleep-2-Peak Reaction Time (ms)   257 2000-01-02 03:03:00
7   Sleep-2-Peak Reaction Time (ms)   268 2000-01-02 02:03:00
8   Sleep-2-Peak Reaction Time (ms)   210 2000-01-02 01:03:00
9   Sleep-2-Peak Reaction Time (ms)   222 2000-01-02 00:03:00
10  Sleep-2-Peak Reaction Time (ms)   237 2000-01-01 23:04:00
11  Sleep-2-Peak Reaction Time (ms)   246 2000-01-01 22:03:00
12  Sleep-2-Peak Reaction Time (ms)   238 2000-01-01 21:06:00
13  Sleep-2-Peak Reaction Time (ms)   268 2000-01-01 20:02:00
14  Sleep-2-Peak Reaction Time (ms)   246 2000-01-01 19:02:00
15  Sleep-2-Peak Reaction Time (ms)   394 2000-01-01 18:03:00
16  Sleep-2-Peak Reaction Time (ms)   254 2000-01-01 17:07:00
17  Sleep-2-Peak Reaction Time (ms)   306 2000-01-01 16:02:00
18  Sleep-2-Peak Reaction Time (ms)   217 2000-01-01 15:02:00
19  Sleep-2-Peak Reaction Time (ms)   238 2000-01-01 14:09:00
20  Sleep-2-Peak Reaction Time (ms)   251 2000-01-01 13:02:00
21  Sleep-2-Peak Reaction Time (ms)   225 2000-01-01 12:02:00
22  Sleep-2-Peak Reaction Time (ms)   296 2000-01-01 11:02:00

In [221]:
reaction_times.sort_values('Timestamp')
reaction_times = reaction_times.reset_index().drop('index',axis=1)
reaction_times = pd.DataFrame({'Timestamp' : reaction_times['Timestamp'], 'Sleep-2-Peak Reaction Time' : reaction_times['Value']})
reaction_times

             Timestamp Sleep-2-Peak Reaction Time
0  2000-01-02 09:02:00                        262
1  2000-01-02 08:02:00                        251
2  2000-01-02 07:02:00                        244
3  2000-01-02 06:02:00                        306
4  2000-01-02 05:01:00                        264
5  2000-01-02 04:04:00                        256
6  2000-01-02 03:03:00                        257
7  2000-01-02 02:03:00                        268
8  2000-01-02 01:03:00                        210
9  2000-01-02 00:03:00                        222
10 2000-01-01 23:04:00                        237
11 2000-01-01 22:03:00                        246
12 2000-01-01 21:06:00                        238
13 2000-01-01 20:02:00                        268
14 2000-01-01 19:02:00                        246
15 2000-01-01 18:03:00                        394
16 2000-01-01 17:07:00                        254
17 2000-01-01 16:02:00                        306
18 2000-01-01 15:02:00                        217
19 2000-01-01 14:09:00                        238
20 2000-01-01 13:02:00                        251
21 2000-01-01 12:02:00                        225
22 2000-01-01 11:02:00                        296

In [222]:
signals = pd.merge_asof(signals, reaction_times.sort_values('Timestamp'), on='Timestamp', direction='nearest')
signals = pd.merge_asof(signals, sleepiness.sort_values('Timestamp'), on='Timestamp', direction='nearest')

In [223]:
signals

,PPG_Raw,PPG_Clean,PPG_Rate,PPG_Quality,PPG_Peaks,Timestamp,Sleep-2-Peak Reaction Time,Stanford Sleepiness Self-Assessment (1-7)
0,686,9.825906,86.612463,0.697393,0,2000-01-01 12:54:44.096662,251,1
1,656,-66.620437,86.612463,0.697393,0,2000-01-01 12:54:44.100672,251,1
2,526,-141.377287,86.612463,0.697393,0,2000-01-01 12:54:44.100672,251,1
3,422,-212.469774,86.612463,0.697393,0,2000-01-01 12:54:44.101674,251,1
4,327,-277.635438,86.612463,0.697393,0,2000-01-01 12:54:44.102676,251,1
...,...,...,...,...,...,...,...,...
999995,623,40.813427,95.559969,0.892090,0,2000-01-01 15:46:17.161904,306,2
999996,615,36.731965,95.559969,0.892090,0,2000-01-01 15:46:17.162907,306,2
999997,608,33.949060,95.559969,0.892090,0,2000-01-01 15:46:17.178287,306,2
999998,602,32.189015,95.559969,0.892090,0,2000-01-01 15:46:17.178287,306,2
999999,596,31.072167,95.559969,0.892090,0,2000-01-01 15:46:17.193917,306,2

In [224]:
for col in signals:
    print(col, ":", signals[col].nunique())

PPG_Raw : 766
PPG_Clean : 1000000
PPG_Rate : 358531
PPG_Quality : 999840
PPG_Peaks : 2
Timestamp : 816290
Sleep-2-Peak Reaction Time : 4
Stanford Sleepiness Self-Assessment (1-7) : 3

In [ ]:
# CNN 1d -> Sarah
# LSTM -> Zoey
# Logistic Regression -> Namie
# Random Forest -> Decision Trees -> Khushi


#voted out : K Nearest Neighbors


# Try boosting